services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: ${DB_POSTGRES_NAME:-sheka}
      POSTGRES_USER: ${DB_POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_POSTGRES_PASSWORD:-postgres}
    ports:
      - "${DB_POSTGRES_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_POSTGRES_USER:-postgres}"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
